# Generated by Django 4.1.13 on 2024-10-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('programa', models.CharField(max_length=100)),
                ('area_programa', models.CharField(max_length=100)),
                ('ejercicio', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('municipio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'beneficiarios',
            },
        ),
    ]
