# Generated by Django 4.1.13 on 2024-10-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefijo', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio_sd', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('programa', models.CharField(max_length=100)),
                ('area_programa', models.CharField(max_length=100)),
                ('ejercicio', models.IntegerField(max_length=4)),
                ('municipio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cve_mpio', models.CharField(max_length=10)),
                ('cve_mpio_full', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('territorio', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'municipios',
            },
        ),
    ]
