# Generated by Django 4.1.13 on 2024-10-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefijo', models.CharField(max_length=10)),
                ('nombreCompleto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefijo', models.CharField(max_length=10)),
                ('nombreCorto', models.CharField(max_length=10)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=50)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.area')),
            ],
        ),
    ]
