# Generated by Django 4.1.13 on 2024-10-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0002_area_programa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='areas',
        ),
        migrations.AlterModelTable(
            name='programa',
            table='programas',
        ),
    ]
